// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwRRHRPSxH1C8_6mAk1hvSmiNISvtoPh8',
    appId: '1:922758528966:web:6d188e3ebbd1d2c424bcc7',
    messagingSenderId: '922758528966',
    projectId: 'sale-pisang-malang',
    authDomain: 'sale-pisang-malang.firebaseapp.com',
    storageBucket: 'sale-pisang-malang.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7cH3_LgjKaVqLOtrhJUjpxgvD0PRefLA',
    appId: '1:922758528966:android:0ed88a62389cef3a24bcc7',
    messagingSenderId: '922758528966',
    projectId: 'sale-pisang-malang',
    storageBucket: 'sale-pisang-malang.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaYDfF_JNllChTfCEAKnUKDiSgkHTyzk8',
    appId: '1:922758528966:ios:5965ae680455776e24bcc7',
    messagingSenderId: '922758528966',
    projectId: 'sale-pisang-malang',
    storageBucket: 'sale-pisang-malang.firebasestorage.app',
    iosBundleId: 'com.example.salePisangMalang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaYDfF_JNllChTfCEAKnUKDiSgkHTyzk8',
    appId: '1:922758528966:ios:5965ae680455776e24bcc7',
    messagingSenderId: '922758528966',
    projectId: 'sale-pisang-malang',
    storageBucket: 'sale-pisang-malang.firebasestorage.app',
    iosBundleId: 'com.example.salePisangMalang',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwRRHRPSxH1C8_6mAk1hvSmiNISvtoPh8',
    appId: '1:922758528966:web:714f195b89eb349224bcc7',
    messagingSenderId: '922758528966',
    projectId: 'sale-pisang-malang',
    authDomain: 'sale-pisang-malang.firebaseapp.com',
    storageBucket: 'sale-pisang-malang.firebasestorage.app',
  );
}
